//HintName: OrderRepository.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class OrderRepository
{
    // TODO: emit body for GetOneAsync (uses this.connection) -- v0.1 Task 4.x
}
