//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<int> InsertWideAsync(global::System.Collections.Generic.IReadOnlyList<global::TestApp.WideRow> @rows, global::System.Threading.CancellationToken @ct)
    {
        var __rows = @rows;
        if (__rows.Count == 0) return 0;
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            const int __chunkSize = 90;
            var __totalAffected = 0;
            var __offset = 0;
            var __remaining = __rows.Count;

            var __sb = new global::System.Text.StringBuilder("INSERT INTO Wide (C1, C2, C3, C4, C5, C6, C7, C8, C9, C10) VALUES ".Length + 64);

            while (__remaining > 0)
            {
                var __thisChunk = __remaining < __chunkSize ? __remaining : __chunkSize;
                await using var __cmd = __conn.CreateCommand();

                __sb.Clear();
                __sb.Append("INSERT INTO Wide (C1, C2, C3, C4, C5, C6, C7, C8, C9, C10) VALUES ");
                for (var __i = 0; __i < __thisChunk; __i++)
                {
                    if (__i > 0) __sb.Append(", ");
                    __sb.Append("(").Append("@C1_").Append(__i).Append(", ").Append("@C2_").Append(__i).Append(", ").Append("@C3_").Append(__i).Append(", ").Append("@C4_").Append(__i).Append(", ").Append("@C5_").Append(__i).Append(", ").Append("@C6_").Append(__i).Append(", ").Append("@C7_").Append(__i).Append(", ").Append("@C8_").Append(__i).Append(", ").Append("@C9_").Append(__i).Append(", ").Append("@C10_").Append(__i).Append(")");
                }
                __cmd.CommandText = __sb.ToString();

                for (var __i = 0; __i < __thisChunk; __i++)
                {
                    var __row = __rows[__offset + __i];
                    var __p_C1_0 = __cmd.CreateParameter();
                    __p_C1_0.ParameterName = "@C1_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C1_0.Value = (object?)__row.C1 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C1_0);
                    var __p_C2_1 = __cmd.CreateParameter();
                    __p_C2_1.ParameterName = "@C2_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C2_1.Value = (object?)__row.C2 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C2_1);
                    var __p_C3_2 = __cmd.CreateParameter();
                    __p_C3_2.ParameterName = "@C3_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C3_2.Value = (object?)__row.C3 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C3_2);
                    var __p_C4_3 = __cmd.CreateParameter();
                    __p_C4_3.ParameterName = "@C4_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C4_3.Value = (object?)__row.C4 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C4_3);
                    var __p_C5_4 = __cmd.CreateParameter();
                    __p_C5_4.ParameterName = "@C5_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C5_4.Value = (object?)__row.C5 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C5_4);
                    var __p_C6_5 = __cmd.CreateParameter();
                    __p_C6_5.ParameterName = "@C6_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C6_5.Value = (object?)__row.C6 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C6_5);
                    var __p_C7_6 = __cmd.CreateParameter();
                    __p_C7_6.ParameterName = "@C7_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C7_6.Value = (object?)__row.C7 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C7_6);
                    var __p_C8_7 = __cmd.CreateParameter();
                    __p_C8_7.ParameterName = "@C8_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C8_7.Value = (object?)__row.C8 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C8_7);
                    var __p_C9_8 = __cmd.CreateParameter();
                    __p_C9_8.ParameterName = "@C9_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C9_8.Value = (object?)__row.C9 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C9_8);
                    var __p_C10_9 = __cmd.CreateParameter();
                    __p_C10_9.ParameterName = "@C10_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_C10_9.Value = (object?)__row.C10 ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_C10_9);
                }

                __totalAffected += await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);

                __offset += __thisChunk;
                __remaining -= __thisChunk;
            }
            return __totalAffected;
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
