//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<int> InsertOrderAsync(int @cust, decimal @total, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "INSERT INTO Orders (CustomerId, Total) VALUES (@cust, @total)";
            var __p_cust = __cmd.CreateParameter();
            __p_cust.ParameterName = "@cust";
            __p_cust.Value = @cust;
            __cmd.Parameters.Add(__p_cust);
            var __p_total = __cmd.CreateParameter();
            __p_total.ParameterName = "@total";
            __p_total.Value = @total;
            __cmd.Parameters.Add(__p_total);
            return await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
