//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::TestApp.OrderStatus> GetStatusAsync(int @id, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Status FROM Orders WHERE Id = @id";
            var __p_id = __cmd.CreateParameter();
            __p_id.ParameterName = "@id";
            __p_id.Value = @id;
            __cmd.Parameters.Add(__p_id);
            var __result = await __cmd.ExecuteScalarAsync(ct).ConfigureAwait(false);
            if (__result is null)
                throw new global::System.InvalidOperationException("Scalar command returned no value; use Task<T?> if null is legal.");
            return (global::TestApp.OrderStatus)global::System.Convert.ToInt32(__result!, global::System.Globalization.CultureInfo.InvariantCulture);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
