//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::TestApp.OrderId> GetMaxIdAsync(global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT MAX(Id) FROM Orders";
            var __result = await __cmd.ExecuteScalarAsync(ct).ConfigureAwait(false);
            if (__result is null)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Scalar command 'TestApp.Repo.GetMaxIdAsync' returned no row, but its return type is the non-nullable 'TestApp.OrderId'. Declare it as 'TestApp.OrderId?' to receive null.");
            if (__result is global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Scalar command 'TestApp.Repo.GetMaxIdAsync' returned NULL, but its return type is the non-nullable 'TestApp.OrderId'. Declare it as 'TestApp.OrderId?' to receive null.");
            return new global::TestApp.OrderId(global::System.Convert.ToInt32(__result!, global::System.Globalization.CultureInfo.InvariantCulture));
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
