//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<decimal> GetTotalAsync(int @customerId, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT SUM(Total) FROM Orders WHERE CustomerId = @customerId";
            var __p_customerId = __cmd.CreateParameter();
            __p_customerId.ParameterName = "customerId";
            __p_customerId.Value = @customerId;
            __cmd.Parameters.Add(__p_customerId);
            var __result = await __cmd.ExecuteScalarAsync(ct).ConfigureAwait(false);
            if (__result is null)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Scalar command 'TestApp.Repo.GetTotalAsync' returned no row, but its return type is the non-nullable 'decimal'. Declare it as 'decimal?' to receive null.");
            if (__result is global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Scalar command 'TestApp.Repo.GetTotalAsync' returned NULL, but its return type is the non-nullable 'decimal'. Declare it as 'decimal?' to receive null.");
            return global::System.Convert.ToDecimal(__result!, global::System.Globalization.CultureInfo.InvariantCulture);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
