//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial global::System.Threading.Tasks.Task<int> InsertOrderAsync(int @cust, decimal @total, global::System.Threading.CancellationToken @ct)
        => throw new global::System.NotImplementedException("[Command] Kind=NonQuery emit lands in v0.4 Phase A.2 / B / C.");
}
