//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<int> UpdateAsync(int @id, global::TestApp.Money @total, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "UPDATE Orders SET Amount = @total_Amount, Currency = @total_Currency WHERE Id = @id";
            var __p_id = __cmd.CreateParameter();
            __p_id.ParameterName = "@id";
            __p_id.Value = @id;
            __cmd.Parameters.Add(__p_id);
            // EmitShape: CompositeBinding total -> global::TestApp.Money (fields: 2)
            var __p_total_Amount = __cmd.CreateParameter();
            __p_total_Amount.ParameterName = "@total_Amount";
            __p_total_Amount.Value = @total.@Amount;
            __cmd.Parameters.Add(__p_total_Amount);
            var __p_total_Currency = __cmd.CreateParameter();
            __p_total_Currency.ParameterName = "@total_Currency";
            __p_total_Currency.Value = @total.@Currency;
            __cmd.Parameters.Add(__p_total_Currency);
            return await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
