//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<int> UpdateAsync(global::TestApp.MoneyWithOrderId @outer, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "UPDATE Orders SET Amount = @outer_Amount, Currency = @outer_Currency WHERE Id = 1";
            // EmitShape: CompositeBinding outer -> global::TestApp.MoneyWithOrderId (fields: 2)
            var __p_outer_Amount = __cmd.CreateParameter();
            __p_outer_Amount.ParameterName = "@outer_Amount";
            __p_outer_Amount.Value = @outer.@Amount;
            __cmd.Parameters.Add(__p_outer_Amount);
            var __p_outer_Currency = __cmd.CreateParameter();
            __p_outer_Currency.ParameterName = "@outer_Currency";
            __p_outer_Currency.Value = @outer.@Currency.Value;
            __cmd.Parameters.Add(__p_outer_Currency);
            return await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
