//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::TestApp.Order?> GetByIdAsync(int @id, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Id, CustomerId, Total FROM Orders WHERE Id = @id";
            var __p_id = __cmd.CreateParameter();
            __p_id.ParameterName = "@id";
            __p_id.Value = @id;
            __cmd.Parameters.Add(__p_id);
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                return null;
            var __Id_ord = __reader.GetOrdinal("Id");
            var __CustomerId_ord = __reader.GetOrdinal("CustomerId");
            var __Total_ord = __reader.GetOrdinal("Total");
            return new global::TestApp.Order(
                __reader.GetInt32(__Id_ord),
                __reader.GetInt32(__CustomerId_ord),
                __reader.GetDecimal(__Total_ord));
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
