//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::TestApp.OrderRow?> SearchAsync(global::TestApp.OrderStatus @status, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Id, Status FROM Orders WHERE Status = @status LIMIT 1";
            var __p_status = __cmd.CreateParameter();
            __p_status.ParameterName = "@status";
            __p_status.Value = @status.ToString();
            __cmd.Parameters.Add(__p_status);
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                return null;
            return new global::TestApp.OrderRow(
                __reader.GetInt32(0),
                global::System.Enum.Parse<global::TestApp.OrderStatus>(__reader.GetString(1)));
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
