//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::TestApp.OrderRow?> SearchAsync(global::TestApp.OrderStatus @status, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Id, Status FROM Orders WHERE Status = @status LIMIT 1";
            var __p_status = __cmd.CreateParameter();
            __p_status.ParameterName = "status";
            __p_status.Value = (int)@status;
            __cmd.Parameters.Add(__p_status);
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                return null;
            try
            {
                return new global::TestApp.OrderRow(
                    __reader.GetInt32(0),
                    (global::TestApp.OrderStatus)__reader.GetInt32(1));
            }
            catch (global::System.Exception __ex) when (__NullColumn(__reader, __ex) is { } __nullColumn)
            {
                throw __nullColumn;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
            static global::System.Exception? __NullColumn(global::System.Data.Async.IAsyncDataRecord __r, global::System.Exception __inner)
            {
                if (__inner is not (global::System.InvalidCastException or global::System.InvalidOperationException or global::System.Data.SqlTypes.SqlNullValueException))
                    return null;
                if (__r.IsDBNull(0))
                    return new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Column '" + __r.GetName(0) + "' is NULL, but parameter 'Id' of 'TestApp.OrderRow' is the non-nullable type 'int'. Declare it as 'int?' to receive null.", __inner);
                if (__r.IsDBNull(1))
                    return new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Column '" + __r.GetName(1) + "' is NULL, but parameter 'Status' of 'TestApp.OrderRow' is the non-nullable type 'TestApp.OrderStatus'. Declare it as 'TestApp.OrderStatus?' to receive null.", __inner);
                return null;
            }
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
