//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<global::TestApp.Order>> ListOrdersAsync(global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Id, Amount, Currency FROM Orders";
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            var __list = new global::System.Collections.Generic.List<global::TestApp.Order>();
            while (await __reader.ReadAsync(ct).ConfigureAwait(false))
            {
                var __Id_ord = __reader.GetOrdinal("Id");
                var __Amount_ord = __reader.GetOrdinal("Amount");
                var __Currency_ord = __reader.GetOrdinal("Currency");
                __list.Add(new global::TestApp.Order(
                    __reader.GetInt32(__Id_ord),
                    new global::TestApp.Money(
                        __reader.GetDecimal(__Amount_ord),
                        __reader.GetString(__Currency_ord))));
            }
            return __list;
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
