//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<global::TestApp.OrderListRow>> ListOrdersAsync(int @limit, int @offset, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Id, CustomerId, Total FROM Orders ORDER BY Id LIMIT @limit OFFSET @offset";
            var __p_limit = __cmd.CreateParameter();
            __p_limit.ParameterName = "@limit";
            __p_limit.Value = @limit;
            __cmd.Parameters.Add(__p_limit);
            var __p_offset = __cmd.CreateParameter();
            __p_offset.ParameterName = "@offset";
            __p_offset.Value = @offset;
            __cmd.Parameters.Add(__p_offset);
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            var __list = new global::System.Collections.Generic.List<global::TestApp.OrderListRow>();
            while (await __reader.ReadAsync(ct).ConfigureAwait(false))
            {
                __list.Add(new global::TestApp.OrderListRow(
                    __reader.GetInt32(0),
                    __reader.GetInt32(1),
                    __reader.GetDecimal(2)));
            }
            return __list;
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
