//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IList<global::TestApp.OrderListRow>> ListOrdersAsync(int @limit, int @offset, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Id, CustomerId, Total FROM Orders ORDER BY Id LIMIT @limit OFFSET @offset";
            var __p_limit = __cmd.CreateParameter();
            __p_limit.ParameterName = "limit";
            __p_limit.Value = @limit;
            __cmd.Parameters.Add(__p_limit);
            var __p_offset = __cmd.CreateParameter();
            __p_offset.ParameterName = "offset";
            __p_offset.Value = @offset;
            __cmd.Parameters.Add(__p_offset);
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            var __list = new global::System.Collections.Generic.List<global::TestApp.OrderListRow>();
            while (await __reader.ReadAsync(ct).ConfigureAwait(false))
            {
                try
                {
                    __list.Add(new global::TestApp.OrderListRow(
                        __reader.GetInt32(0),
                        __reader.GetInt32(1),
                        __reader.GetDecimal(2)));
                }
                catch (global::System.Exception __ex) when (__NullColumn(__reader, __ex) is { } __nullColumn)
                {
                    throw __nullColumn;
                }

                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
                static global::System.Exception? __NullColumn(global::System.Data.Async.IAsyncDataRecord __r, global::System.Exception __inner)
                {
                    if (__inner is not (global::System.InvalidCastException or global::System.InvalidOperationException or global::System.Data.SqlTypes.SqlNullValueException))
                        return null;
                    if (__r.IsDBNull(0))
                        return new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Column '" + __r.GetName(0) + "' is NULL, but parameter 'Id' of 'TestApp.OrderListRow' is the non-nullable type 'int'. Declare it as 'int?' to receive null.", __inner);
                    if (__r.IsDBNull(1))
                        return new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Column '" + __r.GetName(1) + "' is NULL, but parameter 'CustomerId' of 'TestApp.OrderListRow' is the non-nullable type 'int'. Declare it as 'int?' to receive null.", __inner);
                    if (__r.IsDBNull(2))
                        return new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Column '" + __r.GetName(2) + "' is NULL, but parameter 'Total' of 'TestApp.OrderListRow' is the non-nullable type 'decimal'. Declare it as 'decimal?' to receive null.", __inner);
                    return null;
                }
            }
            return __list;
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
