//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<global::TestApp.OrderRow>> ListOrdersAsync(global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Id, Amount, Currency FROM Orders ORDER BY Id";
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            var __list = new global::System.Collections.Generic.List<global::TestApp.OrderRow>();
            while (await __reader.ReadAsync(ct).ConfigureAwait(false))
            {
                __list.Add(new global::TestApp.OrderRow(
                    __reader.GetInt32(0),
                    new global::TestApp.Money(
                        __reader.GetDecimal(1),
                        __reader.GetString(2))));
            }
            return __list;
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
