//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape: composite-factory global::TestApp.Money.FromStorage (factory args: 2)
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::TestApp.Money?> GetTotalAsync(int @id, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Amount, Currency FROM Orders WHERE Id = @id";
            var __p_id = __cmd.CreateParameter();
            __p_id.ParameterName = "@id";
            __p_id.Value = @id;
            __cmd.Parameters.Add(__p_id);
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                return null;
            var __amountText_isNull = __reader.IsDBNull(0);
            var __currency_isNull = __reader.IsDBNull(1);
            if (__amountText_isNull && __currency_isNull) return null;
            if (__amountText_isNull || __currency_isNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException(
                    "Nullable composite 'global::TestApp.Money' has mixed-null columns: " + "amountText.isNull=" + __amountText_isNull + ", " + "currency.isNull=" + __currency_isNull + ". All-or-nothing required.");
            return global::TestApp.Money.FromStorage(
                __reader.GetString(0),
                __reader.GetString(1));
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
