//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(global::TestApp.OrderRow Head, global::System.Collections.Generic.List<global::TestApp.OrderLineRow> Lines)?> GetWithLinesAsync(int @id, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __batch = __conn.CreateBatch();

            var __cmd0 = __batch.CreateBatchCommand();
            __cmd0.CommandText = "SELECT Id, CustomerId, Total FROM Orders WHERE Id = @id";
            var __p_id_0 = __cmd0.CreateParameter();
            __p_id_0.ParameterName = "@id";
            __p_id_0.Value = @id;
            __cmd0.Parameters.Add(__p_id_0);
            __batch.BatchCommands.Add(__cmd0);

            var __cmd1 = __batch.CreateBatchCommand();
            __cmd1.CommandText = "SELECT Sku, Quantity FROM OrderLines WHERE OrderId = @id";
            var __p_id_1 = __cmd1.CreateParameter();
            __p_id_1.ParameterName = "@id";
            __p_id_1.Value = @id;
            __cmd1.Parameters.Add(__p_id_1);
            __batch.BatchCommands.Add(__cmd1);

            await using var __reader = await __batch.ExecuteReaderAsync(ct).ConfigureAwait(false);
            if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                return null;
            var __elem0 = new global::TestApp.OrderRow(
                __reader.GetInt32(0),
                __reader.GetInt32(1),
                __reader.GetDecimal(2));

            if (!await __reader.NextResultAsync(ct).ConfigureAwait(false))
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Expected 2 result sets; got " + 1 + ".");
            var __elem1 = new global::System.Collections.Generic.List<global::TestApp.OrderLineRow>();
            while (await __reader.ReadAsync(ct).ConfigureAwait(false))
            {
                __elem1.Add(new global::TestApp.OrderLineRow(
                    __reader.GetString(0),
                    __reader.GetInt32(1)));
            }
            return (__elem0, __elem1);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
