//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial global::System.Threading.Tasks.Task<(global::TestApp.OrderRow Head, global::System.Collections.Generic.List<global::TestApp.OrderLineRow> Lines)?> GetWithLinesAsync(int @id, global::System.Threading.CancellationToken @ct)
        => throw new global::System.NotImplementedException("MultiResultSet emit lands in v0.3 Phase B.2-B.4");
}
