//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(int Count, decimal? MaxTotal)> GetStatsAsync(global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __batch = __conn.CreateBatch();

            var __cmd0 = __batch.CreateBatchCommand();
            __cmd0.CommandText = "SELECT COUNT(*) FROM Orders";
            __batch.BatchCommands.Add(__cmd0);

            var __cmd1 = __batch.CreateBatchCommand();
            __cmd1.CommandText = "SELECT MAX(Total) FROM Orders";
            __batch.BatchCommands.Add(__cmd1);

            await using var __reader = await __batch.ExecuteReaderAsync(ct).ConfigureAwait(false);
            if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Expected at least one row in result set 0.");
            int __elem0;
            try
            {
                __elem0 = __reader.GetInt32(0);
            }
            catch (global::System.Exception __ex) when (__NullColumn0(__reader, __ex) is { } __nullColumn)
            {
                throw __nullColumn;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
            static global::System.Exception? __NullColumn0(global::System.Data.Async.IAsyncDataRecord __r, global::System.Exception __inner)
            {
                if (__inner is not (global::System.InvalidCastException or global::System.InvalidOperationException or global::System.Data.SqlTypes.SqlNullValueException))
                    return null;
                if (__r.IsDBNull(0))
                    return new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Column '" + __r.GetName(0) + "' is NULL, but tuple element 'Count' is the non-nullable type 'int'. Declare it as 'int?' to receive null.", __inner);
                return null;
            }

            if (!await __reader.NextResultAsync(ct).ConfigureAwait(false))
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Expected 2 result sets; got " + 1 + ".");
            if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Expected at least one row in result set 1.");
            var __elem1 = __reader.IsDBNull(0) ? (decimal?)null : __reader.GetDecimal(0);
            return (__elem0, __elem1);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
