//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<int> InsertAsync(global::System.Collections.Generic.IReadOnlyList<global::TestApp.Row> @rows, global::System.Threading.CancellationToken @ct)
    {
        var __rows = @rows;
        if (__rows.Count == 0) return 0;
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            const int __chunkSize = 450;
            var __totalAffected = 0;
            var __offset = 0;
            var __remaining = __rows.Count;

            var __sb = new global::System.Text.StringBuilder("INSERT INTO T (Qty, Sku) VALUES ".Length + 64);

            while (__remaining > 0)
            {
                var __thisChunk = __remaining < __chunkSize ? __remaining : __chunkSize;
                await using var __cmd = __conn.CreateCommand();

                __sb.Clear();
                __sb.Append("INSERT INTO T (Qty, Sku) VALUES ");
                for (var __i = 0; __i < __thisChunk; __i++)
                {
                    if (__i > 0) __sb.Append(", ");
                    __sb.Append("(").Append("@Qty_").Append(__i).Append(", ").Append("@Sku_").Append(__i).Append(")");
                }
                __cmd.CommandText = __sb.ToString();

                for (var __i = 0; __i < __thisChunk; __i++)
                {
                    var __row = __rows[__offset + __i];
                    var __p_Qty_0 = __cmd.CreateParameter();
                    __p_Qty_0.ParameterName = "Qty_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_Qty_0.Value = (object?)__row.Qty ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_Qty_0);
                    var __p_Sku_1 = __cmd.CreateParameter();
                    __p_Sku_1.ParameterName = "Sku_" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                    __p_Sku_1.Value = (object?)__row.Sku?.Value ?? global::System.DBNull.Value;
                    __cmd.Parameters.Add(__p_Sku_1);
                }

                __totalAffected += await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);

                __offset += __thisChunk;
                __remaining -= __thisChunk;
            }
            return __totalAffected;
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
