//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<int?> GetAgeAsync(global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Age FROM Users LIMIT 1";
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                return null;
            return __reader.IsDBNull(0) ? null : __reader.GetInt32(0);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
