//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<int> InsertAsync(global::TestApp.Line? @line, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "INSERT INTO T (Qty, Sku) VALUES (@line_Qty, @line_Sku)";
            // EmitShape: CompositeBinding line -> global::TestApp.Line (fields: 2)
            if (@line is null)
            {
                var __p_line_Qty = __cmd.CreateParameter();
                __p_line_Qty.ParameterName = "line_Qty";
                __p_line_Qty.Value = global::System.DBNull.Value;
                __cmd.Parameters.Add(__p_line_Qty);
                var __p_line_Sku = __cmd.CreateParameter();
                __p_line_Sku.ParameterName = "line_Sku";
                __p_line_Sku.Value = global::System.DBNull.Value;
                __cmd.Parameters.Add(__p_line_Sku);
            }
            else
            {
                var __p_line_Qty = __cmd.CreateParameter();
                __p_line_Qty.ParameterName = "line_Qty";
                __p_line_Qty.Value = @line.Value.@Qty;
                __cmd.Parameters.Add(__p_line_Qty);
                var __p_line_Sku = __cmd.CreateParameter();
                __p_line_Sku.ParameterName = "line_Sku";
                __p_line_Sku.Value = (object?)@line.Value.@Sku?.Value ?? global::System.DBNull.Value;
                __cmd.Parameters.Add(__p_line_Sku);
            }
            return await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
