//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape: DomainEntity with nullable nested composite (flattened columns: 3)
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<global::TestApp.OrderEntity?> GetByIdAsync(int @id, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Id, Amount, Currency FROM Orders WHERE Id = @id";
            var __p_id = __cmd.CreateParameter();
            __p_id.ParameterName = "@id";
            __p_id.Value = @id;
            __cmd.Parameters.Add(__p_id);
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                return null;
            global::TestApp.Money? __total = default!;
            {
                var __Amount_ord = __reader.GetOrdinal("Amount");
                var __Currency_ord = __reader.GetOrdinal("Currency");
                var __Amount_isNull = __reader.IsDBNull(__Amount_ord);
                var __Currency_isNull = __reader.IsDBNull(__Currency_ord);
                if (__Amount_isNull && __Currency_isNull)
                    __total = null;
                else if (__Amount_isNull || __Currency_isNull)
                    throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException(
                        "Nullable composite 'global::TestApp.Money' has mixed-null columns: " + "Amount.isNull=" + __Amount_isNull + ", " + "Currency.isNull=" + __Currency_isNull + ". All-or-nothing required.");
                else
                    __total = new global::TestApp.Money(
                        __reader.GetDecimal(__Amount_ord),
                        __reader.GetString(__Currency_ord));
            }
            return new global::TestApp.OrderEntity(
                __reader.GetInt32(__reader.GetOrdinal("Id")),
                __total);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
