//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape.SprocWithOutputParams — AllocateAsync
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(int NewId, int? Status)> AllocateAsync(int @newId, int? @status, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "dbo.usp_AllocateId";
            __cmd.CommandType = global::System.Data.CommandType.StoredProcedure;
            var __p_newId = __cmd.CreateParameter();
            __p_newId.ParameterName = "new_id";
            __p_newId.Direction = global::System.Data.ParameterDirection.Output;
            __p_newId.DbType = global::System.Data.DbType.Int32;
            __cmd.Parameters.Add(__p_newId);
            var __p_status = __cmd.CreateParameter();
            __p_status.ParameterName = "status";
            __p_status.Direction = global::System.Data.ParameterDirection.Output;
            __p_status.DbType = global::System.Data.DbType.Int32;
            __cmd.Parameters.Add(__p_status);
            await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
            if (__p_newId.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'dbo.usp_AllocateId' returned NULL for output parameter 'new_id', but tuple element 'NewId' is the non-nullable type 'int'. Declare it as 'int?' to receive null.");
            var __out_NewId = global::System.Convert.ToInt32(__p_newId.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            int? __out_Status = __p_status.Value is null or global::System.DBNull ? null : global::System.Convert.ToInt32(__p_status.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            return (__out_NewId, __out_Status);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
