//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape.SprocWithOutputParams — InsertAsync
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(global::TestApp.OrderRow Result, int NewOrderId, int RETURN_VALUE)> InsertAsync(int @customerId, int @newOrderId, int @RETURN_VALUE, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "usp_InsertOrder";
            __cmd.CommandType = global::System.Data.CommandType.StoredProcedure;
            var __p_customerId = __cmd.CreateParameter();
            __p_customerId.ParameterName = "customerId";
            __p_customerId.Value = @customerId;
            __cmd.Parameters.Add(__p_customerId);
            var __p_newOrderId = __cmd.CreateParameter();
            __p_newOrderId.ParameterName = "newOrderId";
            __p_newOrderId.Direction = global::System.Data.ParameterDirection.Output;
            __p_newOrderId.DbType = global::System.Data.DbType.Int32;
            __cmd.Parameters.Add(__p_newOrderId);
            var __p_RETURN_VALUE = __cmd.CreateParameter();
            __p_RETURN_VALUE.ParameterName = "RETURN_VALUE";
            __p_RETURN_VALUE.Direction = global::System.Data.ParameterDirection.ReturnValue;
            __p_RETURN_VALUE.DbType = global::System.Data.DbType.Int32;
            __cmd.Parameters.Add(__p_RETURN_VALUE);
            global::TestApp.OrderRow __elem0 = default!;
            await using (var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false))
            {
                if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                    throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Expected at least one row in result set 0.");
                __elem0 = new global::TestApp.OrderRow(
                    __reader.GetInt32(0),
                    __reader.GetInt32(1),
                    __reader.GetDecimal(2));
                while (await __reader.ReadAsync(ct).ConfigureAwait(false)) { }
                while (await __reader.NextResultAsync(ct).ConfigureAwait(false))
                {
                    while (await __reader.ReadAsync(ct).ConfigureAwait(false)) { }
                }
            }
            if (__p_newOrderId.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_InsertOrder' returned NULL for output parameter 'newOrderId', but tuple element 'NewOrderId' is the non-nullable type 'int'. Declare it as 'int?' to receive null.");
            var __out_NewOrderId = global::System.Convert.ToInt32(__p_newOrderId.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            if (__p_RETURN_VALUE.Value is null)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("The provider did not set the RETURN value of stored procedure 'usp_InsertOrder' into parameter 'RETURN_VALUE'. Only SQL Server procedures have a RETURN value.");
            if (__p_RETURN_VALUE.Value is global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_InsertOrder' returned a NULL RETURN value into parameter 'RETURN_VALUE', but tuple element 'RETURN_VALUE' is the non-nullable type 'int'. Declare it as 'int?' to receive null.");
            var __out_RETURN_VALUE = global::System.Convert.ToInt32(__p_RETURN_VALUE.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            return (__elem0, __out_NewOrderId, __out_RETURN_VALUE);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
