//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape.SprocWithOutputParams — TemporalAsync
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(global::System.DateTime Day, global::System.DateTimeOffset Stamp, global::System.TimeSpan Span, global::System.DateTimeOffset? MaybeStamp, global::System.TimeSpan? MaybeSpan)> TemporalAsync(global::System.DateTime @day, global::System.DateTimeOffset @stamp, global::System.TimeSpan @span, global::System.DateTimeOffset? @maybeStamp, global::System.TimeSpan? @maybeSpan, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "usp_Temporal";
            __cmd.CommandType = global::System.Data.CommandType.StoredProcedure;
            var __p_day = __cmd.CreateParameter();
            __p_day.ParameterName = "day";
            __p_day.Direction = global::System.Data.ParameterDirection.Output;
            __p_day.DbType = global::System.Data.DbType.DateTime2;
            __cmd.Parameters.Add(__p_day);
            var __p_stamp = __cmd.CreateParameter();
            __p_stamp.ParameterName = "stamp";
            __p_stamp.Direction = global::System.Data.ParameterDirection.Output;
            __p_stamp.DbType = global::System.Data.DbType.DateTimeOffset;
            __cmd.Parameters.Add(__p_stamp);
            var __p_span = __cmd.CreateParameter();
            __p_span.ParameterName = "span";
            __p_span.Direction = global::System.Data.ParameterDirection.Output;
            __p_span.DbType = global::System.Data.DbType.Time;
            __cmd.Parameters.Add(__p_span);
            var __p_maybeStamp = __cmd.CreateParameter();
            __p_maybeStamp.ParameterName = "maybeStamp";
            __p_maybeStamp.Direction = global::System.Data.ParameterDirection.Output;
            __p_maybeStamp.DbType = global::System.Data.DbType.DateTimeOffset;
            __cmd.Parameters.Add(__p_maybeStamp);
            var __p_maybeSpan = __cmd.CreateParameter();
            __p_maybeSpan.ParameterName = "maybeSpan";
            __p_maybeSpan.Direction = global::System.Data.ParameterDirection.Output;
            __p_maybeSpan.DbType = global::System.Data.DbType.Time;
            __cmd.Parameters.Add(__p_maybeSpan);
            await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
            if (__p_day.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_Temporal' returned NULL for output parameter 'day', but tuple element 'Day' is the non-nullable type 'System.DateTime'. Declare it as 'System.DateTime?' to receive null.");
            var __out_Day = (__p_day.Value! switch { global::System.DateOnly __v => __v.ToDateTime(global::System.TimeOnly.MinValue), var __v => global::System.Convert.ToDateTime(__v, global::System.Globalization.CultureInfo.InvariantCulture) });
            if (__p_stamp.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_Temporal' returned NULL for output parameter 'stamp', but tuple element 'Stamp' is the non-nullable type 'System.DateTimeOffset'. Declare it as 'System.DateTimeOffset?' to receive null.");
            var __out_Stamp = (__p_stamp.Value! switch { global::System.DateTimeOffset __v => __v, global::System.DateTime __v when __v.Kind != global::System.DateTimeKind.Unspecified => new global::System.DateTimeOffset(__v), var __v => (global::System.DateTimeOffset)__v });
            if (__p_span.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_Temporal' returned NULL for output parameter 'span', but tuple element 'Span' is the non-nullable type 'System.TimeSpan'. Declare it as 'System.TimeSpan?' to receive null.");
            var __out_Span = (__p_span.Value! switch { global::System.TimeSpan __v => __v, global::System.TimeOnly __v => __v.ToTimeSpan(), var __v => (global::System.TimeSpan)__v });
            global::System.DateTimeOffset? __out_MaybeStamp = __p_maybeStamp.Value is null or global::System.DBNull ? null : (__p_maybeStamp.Value! switch { global::System.DateTimeOffset __v => __v, global::System.DateTime __v when __v.Kind != global::System.DateTimeKind.Unspecified => new global::System.DateTimeOffset(__v), var __v => (global::System.DateTimeOffset)__v });
            global::System.TimeSpan? __out_MaybeSpan = __p_maybeSpan.Value is null or global::System.DBNull ? null : (__p_maybeSpan.Value! switch { global::System.TimeSpan __v => __v, global::System.TimeOnly __v => __v.ToTimeSpan(), var __v => (global::System.TimeSpan)__v });
            return (__out_Day, __out_Stamp, __out_Span, __out_MaybeStamp, __out_MaybeSpan);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
