//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape.SprocWithOutputParams — InsertAsync
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(int NewOrderId, int Status)> InsertAsync(int @customerId, int @newOrderId, int @status, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "usp_InsertOrder";
            __cmd.CommandType = global::System.Data.CommandType.StoredProcedure;
            var __p_customerId = __cmd.CreateParameter();
            __p_customerId.ParameterName = "@customerId";
            __p_customerId.Value = @customerId;
            __cmd.Parameters.Add(__p_customerId);
            var __p_newOrderId = __cmd.CreateParameter();
            __p_newOrderId.ParameterName = "@newOrderId";
            __p_newOrderId.Direction = global::System.Data.ParameterDirection.Output;
            __cmd.Parameters.Add(__p_newOrderId);
            var __p_status = __cmd.CreateParameter();
            __p_status.ParameterName = "@status";
            __p_status.Direction = global::System.Data.ParameterDirection.Output;
            __cmd.Parameters.Add(__p_status);
            await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
            var __out_NewOrderId = global::System.Convert.ToInt32(__p_newOrderId.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            var __out_Status = global::System.Convert.ToInt32(__p_status.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            return (__out_NewOrderId, __out_Status);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
