//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape.SprocWithOutputParams — ShiftAsync
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(global::System.DateOnly Day, global::System.TimeOnly Start, global::System.DateOnly? MaybeDay, global::System.TimeOnly? MaybeStart)> ShiftAsync(global::System.DateOnly @day, global::System.TimeOnly @start, global::System.DateOnly? @maybeDay, global::System.TimeOnly? @maybeStart, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "usp_Shift";
            __cmd.CommandType = global::System.Data.CommandType.StoredProcedure;
            var __p_day = __cmd.CreateParameter();
            __p_day.ParameterName = "day";
            __p_day.Direction = global::System.Data.ParameterDirection.Output;
            __p_day.DbType = global::System.Data.DbType.Date;
            __cmd.Parameters.Add(__p_day);
            var __p_start = __cmd.CreateParameter();
            __p_start.ParameterName = "start";
            __p_start.Direction = global::System.Data.ParameterDirection.Output;
            __p_start.DbType = global::System.Data.DbType.Time;
            __cmd.Parameters.Add(__p_start);
            var __p_maybeDay = __cmd.CreateParameter();
            __p_maybeDay.ParameterName = "maybeDay";
            __p_maybeDay.Direction = global::System.Data.ParameterDirection.Output;
            __p_maybeDay.DbType = global::System.Data.DbType.Date;
            __cmd.Parameters.Add(__p_maybeDay);
            var __p_maybeStart = __cmd.CreateParameter();
            __p_maybeStart.ParameterName = "maybeStart";
            __p_maybeStart.Direction = global::System.Data.ParameterDirection.Output;
            __p_maybeStart.DbType = global::System.Data.DbType.Time;
            __cmd.Parameters.Add(__p_maybeStart);
            await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
            if (__p_day.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_Shift' returned NULL for output parameter 'day', but tuple element 'Day' is the non-nullable type 'System.DateOnly'. Declare it as 'System.DateOnly?' to receive null.");
            var __out_Day = (__p_day.Value! switch { global::System.DateOnly __v => __v, global::System.DateTime __v when __v.TimeOfDay == global::System.TimeSpan.Zero => global::System.DateOnly.FromDateTime(__v), string __v => global::System.DateOnly.Parse(__v, global::System.Globalization.CultureInfo.InvariantCulture), double __v => global::System.DateOnly.FromDateTime(new global::System.DateTime(checked(((long)((double)__v * 86400000.0 + 0.5) - 148731163200000L) * global::System.TimeSpan.TicksPerMillisecond))), long __v => global::System.DateOnly.FromDateTime(new global::System.DateTime(checked(((long)((double)__v * 86400000.0 + 0.5) - 148731163200000L) * global::System.TimeSpan.TicksPerMillisecond))), var __v => (global::System.DateOnly)__v });
            if (__p_start.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_Shift' returned NULL for output parameter 'start', but tuple element 'Start' is the non-nullable type 'System.TimeOnly'. Declare it as 'System.TimeOnly?' to receive null.");
            var __out_Start = (__p_start.Value! switch { global::System.TimeOnly __v => __v, global::System.TimeSpan __v => global::System.TimeOnly.FromTimeSpan(__v), string __v => global::System.TimeOnly.Parse(__v, global::System.Globalization.CultureInfo.InvariantCulture), var __v => (global::System.TimeOnly)__v });
            global::System.DateOnly? __out_MaybeDay = __p_maybeDay.Value is null or global::System.DBNull ? null : (__p_maybeDay.Value! switch { global::System.DateOnly __v => __v, global::System.DateTime __v when __v.TimeOfDay == global::System.TimeSpan.Zero => global::System.DateOnly.FromDateTime(__v), string __v => global::System.DateOnly.Parse(__v, global::System.Globalization.CultureInfo.InvariantCulture), double __v => global::System.DateOnly.FromDateTime(new global::System.DateTime(checked(((long)((double)__v * 86400000.0 + 0.5) - 148731163200000L) * global::System.TimeSpan.TicksPerMillisecond))), long __v => global::System.DateOnly.FromDateTime(new global::System.DateTime(checked(((long)((double)__v * 86400000.0 + 0.5) - 148731163200000L) * global::System.TimeSpan.TicksPerMillisecond))), var __v => (global::System.DateOnly)__v });
            global::System.TimeOnly? __out_MaybeStart = __p_maybeStart.Value is null or global::System.DBNull ? null : (__p_maybeStart.Value! switch { global::System.TimeOnly __v => __v, global::System.TimeSpan __v => global::System.TimeOnly.FromTimeSpan(__v), string __v => global::System.TimeOnly.Parse(__v, global::System.Globalization.CultureInfo.InvariantCulture), var __v => (global::System.TimeOnly)__v });
            return (__out_Day, __out_Start, __out_MaybeDay, __out_MaybeStart);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
