//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape.SprocWithOutputParams — RunAsync
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(string Label, int Count, global::TestApp.Status State, global::TestApp.Named Name, global::TestApp.OrderId OrderRef, string? Note, int? Maybe)> RunAsync(string @label, int @count, global::TestApp.Status @state, global::TestApp.Named @name, global::TestApp.OrderId @orderRef, string? @note, int? @maybe, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "dbo.usp_Outputs";
            __cmd.CommandType = global::System.Data.CommandType.StoredProcedure;
            var __p_label = __cmd.CreateParameter();
            __p_label.ParameterName = "label";
            __p_label.Direction = global::System.Data.ParameterDirection.Output;
            __p_label.DbType = global::System.Data.DbType.String;
            __p_label.Size = -1;
            __cmd.Parameters.Add(__p_label);
            var __p_count = __cmd.CreateParameter();
            __p_count.ParameterName = "count";
            __p_count.Direction = global::System.Data.ParameterDirection.Output;
            __p_count.DbType = global::System.Data.DbType.Int32;
            __cmd.Parameters.Add(__p_count);
            var __p_state = __cmd.CreateParameter();
            __p_state.ParameterName = "state";
            __p_state.Direction = global::System.Data.ParameterDirection.Output;
            __p_state.DbType = global::System.Data.DbType.Int32;
            __cmd.Parameters.Add(__p_state);
            var __p_name = __cmd.CreateParameter();
            __p_name.ParameterName = "name";
            __p_name.Direction = global::System.Data.ParameterDirection.Output;
            __p_name.DbType = global::System.Data.DbType.String;
            __p_name.Size = -1;
            __cmd.Parameters.Add(__p_name);
            var __p_orderRef = __cmd.CreateParameter();
            __p_orderRef.ParameterName = "orderRef";
            __p_orderRef.Direction = global::System.Data.ParameterDirection.Output;
            __p_orderRef.DbType = global::System.Data.DbType.Int32;
            __cmd.Parameters.Add(__p_orderRef);
            var __p_note = __cmd.CreateParameter();
            __p_note.ParameterName = "note";
            __p_note.Direction = global::System.Data.ParameterDirection.Output;
            __p_note.DbType = global::System.Data.DbType.String;
            __p_note.Size = -1;
            __cmd.Parameters.Add(__p_note);
            var __p_maybe = __cmd.CreateParameter();
            __p_maybe.ParameterName = "maybe";
            __p_maybe.Direction = global::System.Data.ParameterDirection.Output;
            __p_maybe.DbType = global::System.Data.DbType.Int32;
            __cmd.Parameters.Add(__p_maybe);
            await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
            if (__p_label.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'dbo.usp_Outputs' returned NULL for output parameter 'label', but tuple element 'Label' is the non-nullable type 'string'. Declare it as 'string?' to receive null.");
            var __out_Label = global::System.Convert.ToString(__p_label.Value!, global::System.Globalization.CultureInfo.InvariantCulture)!;
            if (__p_count.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'dbo.usp_Outputs' returned NULL for output parameter 'count', but tuple element 'Count' is the non-nullable type 'int'. Declare it as 'int?' to receive null.");
            var __out_Count = global::System.Convert.ToInt32(__p_count.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            if (__p_state.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'dbo.usp_Outputs' returned NULL for output parameter 'state', but tuple element 'State' is the non-nullable type 'TestApp.Status'. Declare it as 'TestApp.Status?' to receive null.");
            var __out_State = (global::TestApp.Status)global::System.Convert.ToInt32(__p_state.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            if (__p_name.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'dbo.usp_Outputs' returned NULL for output parameter 'name', but tuple element 'Name' is the non-nullable type 'TestApp.Named'. Declare it as 'TestApp.Named?' to receive null.");
            var __out_Name = global::System.Enum.Parse<global::TestApp.Named>(global::System.Convert.ToString(__p_name.Value!, global::System.Globalization.CultureInfo.InvariantCulture)!);
            if (__p_orderRef.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'dbo.usp_Outputs' returned NULL for output parameter 'orderRef', but tuple element 'OrderRef' is the non-nullable type 'TestApp.OrderId'. Declare it as 'TestApp.OrderId?' to receive null.");
            var __out_OrderRef = new global::TestApp.OrderId(global::System.Convert.ToInt32(__p_orderRef.Value!, global::System.Globalization.CultureInfo.InvariantCulture));
            string? __out_Note = __p_note.Value is null or global::System.DBNull ? null : global::System.Convert.ToString(__p_note.Value!, global::System.Globalization.CultureInfo.InvariantCulture)!;
            int? __out_Maybe = __p_maybe.Value is null or global::System.DBNull ? null : global::System.Convert.ToInt32(__p_maybe.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            return (__out_Label, __out_Count, __out_State, __out_Name, __out_OrderRef, __out_Note, __out_Maybe);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
