//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape.SprocWithOutputParams — RunAsync
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(global::System.TimeSpan Span, global::System.TimeSpan Fixed)> RunAsync(global::System.TimeSpan @span, global::System.TimeSpan @fixed, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "usp_InOutSpan";
            __cmd.CommandType = global::System.Data.CommandType.StoredProcedure;
            var __p_span = __cmd.CreateParameter();
            __p_span.ParameterName = "span";
            __p_span.Direction = global::System.Data.ParameterDirection.InputOutput;
            __p_span.Value = @span;
            __cmd.Parameters.Add(__p_span);
            var __p_fixed = __cmd.CreateParameter();
            __p_fixed.ParameterName = "fixed";
            __p_fixed.Direction = global::System.Data.ParameterDirection.Output;
            __p_fixed.DbType = global::System.Data.DbType.Time;
            __cmd.Parameters.Add(__p_fixed);
            await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
            if (__p_span.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_InOutSpan' returned NULL for output parameter 'span', but tuple element 'Span' is the non-nullable type 'System.TimeSpan'. Declare it as 'System.TimeSpan?' to receive null.");
            var __out_Span = (__p_span.Value! switch { global::System.TimeSpan __v => __v, global::System.TimeOnly __v => __v.ToTimeSpan(), string __v => global::System.TimeSpan.Parse(__v, global::System.Globalization.CultureInfo.InvariantCulture), double __v => global::System.TimeSpan.FromDays(__v), long __v => global::System.TimeSpan.FromDays((double)__v), var __v => (global::System.TimeSpan)__v });
            if (__p_fixed.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_InOutSpan' returned NULL for output parameter 'fixed', but tuple element 'Fixed' is the non-nullable type 'System.TimeSpan'. Declare it as 'System.TimeSpan?' to receive null.");
            var __out_Fixed = (__p_fixed.Value! switch { global::System.TimeSpan __v => __v, global::System.TimeOnly __v => __v.ToTimeSpan(), string __v => global::System.TimeSpan.Parse(__v, global::System.Globalization.CultureInfo.InvariantCulture), double __v => global::System.TimeSpan.FromDays(__v), long __v => global::System.TimeSpan.FromDays((double)__v), var __v => (global::System.TimeSpan)__v });
            return (__out_Span, __out_Fixed);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
