//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape.SprocWithOutputParams — InsertAsync
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(global::TestApp.OrderRow Result, int? OptionalCount)> InsertAsync(int @customerId, int? @optionalCount, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "usp_InsertOrderMaybeCount";
            __cmd.CommandType = global::System.Data.CommandType.StoredProcedure;
            var __p_customerId = __cmd.CreateParameter();
            __p_customerId.ParameterName = "@customerId";
            __p_customerId.Value = @customerId;
            __cmd.Parameters.Add(__p_customerId);
            var __p_optionalCount = __cmd.CreateParameter();
            __p_optionalCount.ParameterName = "@optionalCount";
            __p_optionalCount.Direction = global::System.Data.ParameterDirection.Output;
            __cmd.Parameters.Add(__p_optionalCount);
            global::TestApp.OrderRow __elem0 = default!;
            await using (var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false))
            {
                if (!await __reader.ReadAsync(ct).ConfigureAwait(false))
                    throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Expected at least one row in result set 0.");
                __elem0 = new global::TestApp.OrderRow(
                    __reader.GetInt32(0),
                    __reader.GetInt32(1),
                    __reader.GetDecimal(2));
                while (await __reader.ReadAsync(ct).ConfigureAwait(false)) { }
                while (await __reader.NextResultAsync(ct).ConfigureAwait(false))
                {
                    while (await __reader.ReadAsync(ct).ConfigureAwait(false)) { }
                }
            }
            int? __out_OptionalCount = __p_optionalCount.Value is global::System.DBNull ? null : global::System.Convert.ToInt32(__p_optionalCount.Value!, global::System.Globalization.CultureInfo.InvariantCulture);
            return (__elem0, __out_OptionalCount);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
