//HintName: TestApp.Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    // EmitShape.SprocWithOutputParams — RunAsync
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<(global::System.TimeOnly Start, global::System.TimeOnly Fixed)> RunAsync(global::System.TimeOnly @start, global::System.TimeOnly @fixed, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "usp_InOutClock";
            __cmd.CommandType = global::System.Data.CommandType.StoredProcedure;
            var __p_start = __cmd.CreateParameter();
            __p_start.ParameterName = "start";
            __p_start.Direction = global::System.Data.ParameterDirection.InputOutput;
            __p_start.DbType = global::System.Data.DbType.Time;
            __p_start.Value = @start;
            __cmd.Parameters.Add(__p_start);
            var __p_fixed = __cmd.CreateParameter();
            __p_fixed.ParameterName = "fixed";
            __p_fixed.Direction = global::System.Data.ParameterDirection.Output;
            __p_fixed.DbType = global::System.Data.DbType.Time;
            __cmd.Parameters.Add(__p_fixed);
            await __cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
            if (__p_start.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_InOutClock' returned NULL for output parameter 'start', but tuple element 'Start' is the non-nullable type 'System.TimeOnly'. Declare it as 'System.TimeOnly?' to receive null.");
            var __out_Start = (__p_start.Value! switch { global::System.TimeOnly __v => __v, global::System.TimeSpan __v => global::System.TimeOnly.FromTimeSpan(__v), string __v => global::System.TimeOnly.Parse(__v, global::System.Globalization.CultureInfo.InvariantCulture), var __v => (global::System.TimeOnly)__v });
            if (__p_fixed.Value is null or global::System.DBNull)
                throw new global::ZeroAlloc.ORM.ZeroAllocOrmMaterializationException("Stored procedure 'usp_InOutClock' returned NULL for output parameter 'fixed', but tuple element 'Fixed' is the non-nullable type 'System.TimeOnly'. Declare it as 'System.TimeOnly?' to receive null.");
            var __out_Fixed = (__p_fixed.Value! switch { global::System.TimeOnly __v => __v, global::System.TimeSpan __v => global::System.TimeOnly.FromTimeSpan(__v), string __v => global::System.TimeOnly.Parse(__v, global::System.Globalization.CultureInfo.InvariantCulture), var __v => (global::System.TimeOnly)__v });
            return (__out_Start, __out_Fixed);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
