//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Collections.Generic.IAsyncEnumerable<global::TestApp.OrderRow> StreamAsync(global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.CommandText = "SELECT Id, CustomerId, Total FROM Orders ORDER BY Id";
            await using var __reader = await __cmd.ExecuteReaderAsync(ct).ConfigureAwait(false);
            while (await __reader.ReadAsync(ct).ConfigureAwait(false))
            {
                yield return new global::TestApp.OrderRow(
                    __reader.GetInt32(0),
                    __reader.GetInt32(1),
                    __reader.GetDecimal(2));
            }
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
