//HintName: Repo.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp;

partial class Repo
{
    [global::System.CodeDom.Compiler.GeneratedCode("ZeroAlloc.ORM.Generator", "0.1.0")]
    public partial async global::System.Threading.Tasks.Task<int> InsertOrderAsync(int @customerId, IAsyncDbTransaction @tx, global::System.Threading.CancellationToken @ct)
    {
        var __conn = @connection;
        var __openedHere = __conn.State != global::System.Data.ConnectionState.Open;
        if (__openedHere) await __conn.OpenAsync(ct).ConfigureAwait(false);
        try
        {
            await using var __cmd = __conn.CreateCommand();
            __cmd.Transaction = @tx;
            __cmd.CommandText = "INSERT INTO Orders (CustomerId) VALUES (@customerId) RETURNING Id";
            var __p_customerId = __cmd.CreateParameter();
            __p_customerId.ParameterName = "@customerId";
            __p_customerId.Value = @customerId;
            __cmd.Parameters.Add(__p_customerId);
            var __result = await __cmd.ExecuteScalarAsync(ct).ConfigureAwait(false);
            if (__result is null)
                throw new global::System.InvalidOperationException("Identity command returned no value; the SQL must include a RETURNING / SCOPE_IDENTITY() clause that produces a non-null value.");
            return global::System.Convert.ToInt32(__result!, global::System.Globalization.CultureInfo.InvariantCulture);
        }
        finally
        {
            if (__openedHere) await __conn.CloseAsync().ConfigureAwait(false);
        }
    }
}
